### ISSUE TITLE
Suggestions : Allow to pick any milestones/awards whatever map is selected

### ISSUE THREAD

**Issue by mwestphal** [ssimeonoff/ssimeonoff.github.io#13]
The submit game form does not support randomized milestones and awards, would that be possible ?

**Comment by ssimeonoff** [comment]
No. Thoutht about it after I did the MA Randomizer. 

If it is available to select random M&A, then , manually all random M&A should be filled then and then selecting the used ones, in more to calculate the usability percentages.  It is doable, but overcomplicates eveything, plus the Form will have to be bigger.

**Comment by mwestphal** [comment]
alright, thanks for considering it.
