### ISSUE TITLE
Suggestions : Add an optional "name" field for each player

### ISSUE THREAD

**Issue by mwestphal** [ssimeonoff/ssimeonoff.github.io#14]
When looking back into our previous game, I sometimes have a hard time figuring out which game was won by who in my group. Could you add this info ?

**Comment by ssimeonoff** [comment]
I added recently on the Submit page a grey highlight of the personal position. 
So at least you can see if if you own standings.

**Comment by mwestphal** [comment]
Yes ! I've seen that, thanks.

**Comment by mwestphal** [comment]
You don't think that's worth it ?
