### ISSUE TITLE
Can not submit game. Country undefined.

### ISSUE THREAD

**Issue by isobolev** [ssimeonoff/ssimeonoff.github.io#16]
got undefined in console log from line main.js:54. For some reason the country field is undefined and firebase fails with the following error:
`firebase.js:1 Uncaught Error: Reference.set failed: First argument contains undefined in property 'games-production.-LsgdF8B52m_9-RwYPJ_.country'`

the country is Ukraine. Please add a check that the country is defined. If not maybe some default country can be used.

Thanks

**Comment by ssimeonoff** [comment]
hmm, weird, there is a default country "TM" with the terraforming look-alike icon.
