### ISSUE TITLE
Sorting cards by MC up/down should refresh pagination

### ISSUE THREAD

**Issue by fggrimshaw** [ssimeonoff/ssimeonoff.github.io#20]
Setting the sort to MC UP/Down only sorts the visible cards.  Only after modifying the filters/queries will it sort across all cards.

Reproduction:
1. Go to the cards list https://ssimeonoff.github.io/cards-list
2. In the content menu, set to sort by MC UP

We should expect to see a 0 cost card first, instead we see Search for Life (the cheapest card on the first page when sorting by ID). After adding and removing a filter it will properly show a 0 cost card first

**Comment by ssimeonoff** [comment]
fixed

**Comment by fggrimshaw** [comment]
Awesome. Thanks for making such a great tool, it's been invaluable in discussions about TM between my friends
