### ISSUE TITLE
Could not submit solo game score

### ISSUE THREAD

**Issue by lostgrail** [ssimeonoff/ssimeonoff.github.io#21]
Hi, 

I recently tried to submit my solo game score, and when I tried to submit the score value became highlighted in red (like I made an error)

I didn’t poke at the source code, but is there score validation that would prevent a low score from being added. My solo score came to 58 points. I was playing CE, Prelude, and Turmoil. (Lakefront Resorts).

Thanks!

**Comment by ssimeonoff** [comment]
Min valid score is 60.  Maybe I should change it to 56, which is the theoretical minimum in TF ALL.

**Comment by lostgrail** [comment]
I think the theoretical minimum is lower.
14 Solo start
+42 TR (TR All objective)
-3 (Turmoil events that increase global parameters: Democratic Reform and Patera Boring)
-13 (Turmoil TR adjustment per turn)
-4 (Turmoil events Separatist Movement and World Government Directives)
-9 Various cards with negative score that make sense in solo
-2 Pristar Corp 
Which is a floor of 23 points. 

And that’s not including Venus Next or Colonies (since I didn’t play with them in this game)

I’ll concede that I had an anomalously low scoring solo game, and maybe Turmoil expansion by itself is oddly low scoring (I got hit by both of the Turmoil cards that drop TR though)

Thanks

**Comment by lostgrail** [comment]
I apologize if my last message was a little terse: I was on my way out the door for work, and was trying to type and shuffle through the cards quickly. :)

Turmoil seriously drops the floor out of your theoretical minimum score for solo. There is a built-in -1 TR/turn, and cards that both add to global parameters and take away TR in the Global Event Deck. 

Looking at the Venus Next and Colonies cards (thanks to your database), there’s an extra -2 VP in cards from Colonies that could drop your score, and the whole Venus Next Expansion doesn’t have cards that affect this, it would seem to raise the theoretical floor by 2 when you factor in WG Terraforming and the Venus board (+15 TR for Terraforming Venus, -13 for WG Terraforming). However, if WG Terraforming hits the two bonuses that contribute to other parameters, then the potential minimum drops by another two to as much as -15. So for theoretical minimums it’s neutral. 

Preludes shortens the Max Game length, so the TR lost to inflation and WG Terraforming is reduced by 2 for each of Venus Next and Turmoil that are also included.

I think we can say, based on all this, that one could have as low a score as 19 (all expansions except Preludes). And it is highly dependant on the expansions being played with. 

To break it down by expansion:
* Base Game is minimum 51 (14 base + 42 TR from Terraforming, -5 from the cards with negative VP)
* Corporate Era has a total of -7 in negative VP cards.
* Venus Next has no effect on minim score. 
* Colonies adds two negative VP cards, so it applies a -2 to minimum score
* Preludes actually raises the minimum score by 2 for each of Venus and Turmoil, because there are two less turns for the things that lose you TR to happen in. 
* Turmoil is potentially lowering the minimum score by -23 (-13 for 13 generations of lost TR, six TR possibly lost from global events, three TR you can’t gain if the events that raise heat or place an ocean come up, and I think there’s one possibly useful negative VP card)

For the record, the game I had a score of 58 in was one with CE, Preludes, and Turmoil, so my theoretical minimum was 23. 

I hope this helps update the minimums for valid game scores.

**Comment by lostgrail** [comment]
Forgot to include Pristar in my estimate, where you start the game with -2 TR. Absolute floor is 17

**Comment by ssimeonoff** [comment]
Reduced ti min limit to 50. If you win with under 50, consider it a loss. :)
