### ISSUE TITLE
Account auth not working during submittal

### ISSUE THREAD

**Issue by ddiera** [ssimeonoff/ssimeonoff.github.io#22]
Interface states user is authenticated and submitting the game data will be assigned to his stats but it does not go through.

Issue is present for 24h+ now.

**Comment by ssimeonoff** [comment]
Ouch, yes..
I think I fixed it. Try again now.

**Comment by ddiera** [comment]
doesn't seem to be working :(

game history populates the database but the submitter profile is not shown, nor does it list the game under "my stats"

**Comment by ssimeonoff** [comment]
Probably I have messed up something, but it hard to tell what. 

1. Open https://ssimeonoff.github.io/login and login again and see if it is ok then.

2. Inspect the browser's console and see if there is some error.  (on Chrome, you can do mouse right click and choose "Inspect")

**Comment by ssimeonoff** [comment]
Fixed now. For real.
