### ISSUE TITLE
New games won't submit

### ISSUE THREAD

**Issue by ethanfuerst** [ssimeonoff/ssimeonoff.github.io#23]
After I submit a new game to the database when I am logged in to my gmail account, the games don't show up in my personal stats. Is this an issue you are aware of?

By the way, I love the site! My friends and I use it extensively.

**Comment by ssimeonoff** [comment]
You need to go the Stats page and fetch the new games. 

The displayed games are the ones stored on your browser.

**Comment by ethanfuerst** [comment]
I've submitted multiple games and still only 2 show up when I filter by my games

**Comment by ssimeonoff** [comment]
I see 14 games submitted by you - https://ssimeonoff.github.io/stats#ethan
Last one was 2 days ago.

"Fetch new game" to get all new submitted games.

**Comment by ethanfuerst** [comment]
Oh, gotcha. I wasn't doing that step and just clicking the 'My Stats' button. Thanks!
