### ISSUE TITLE
Normalize Corporation Win Rates?

### ISSUE THREAD

**Issue by merlinstardust** [ssimeonoff/ssimeonoff.github.io#26]
I just discovered this and absolutely love this project. My friends and I are obsessed with the game and we will absolutely enjoy this site.

When looking at the win rates for corporations, I noticed that sorting by percentage is somewhat deceptive. For instance, sorting the 5 player column currently puts Astrodrill on top with a 67% win rate which is 27% higher than Beginner Corporation at 40%. This makes it seem like the best choice for 5 player games until I looked and saw that it had only been played in 3 games.

Is there any way to somehow sort by some kind of normalized win rate such that it accounts for both number of games played and number of games won? Or if not, could that be added?

One other, unrelated question: where do you store your data and what keeps my login secure?

**Comment by ssimeonoff** [comment]
@merlinpatt 
the auth is via firebase  - https://firebase.google.com/support/privacy/

I never thought about the data normalization much, but now spends the free time in another project. 
If you think my project is cool, wait to see this one:
https://github.com/bafolts/terraforming-mars

**Comment by merlinstardust** [comment]
I'd be happy to look into it and write it myself. I don't know yet when I would get to it, but if I were to make a PR for data normalization, is that something you would be willing to look at and merge in?

That new project is awesome. Have you encountered any resistance or legal trouble from Fryx Games on making an online version of the game? I'm asking because I'm considering making an online version of another game but don't want to get into some kind of legal battle

(I'll close this issue for now since it's not a current issue)
