### ISSUE TITLE
Stat submission and stats aren't working on Chrome.

### ISSUE THREAD

**Issue by Nathanpmyoung** [ssimeonoff/ssimeonoff.github.io#29]
Just stays like this

![image](https://user-images.githubusercontent.com/20482100/106383249-d399b700-63bc-11eb-93bc-494551697533.png)

**Comment by ssimeonoff** [comment]
It is because the traffic limit is exceeded and Google disables the database until the next month. I use only 10GB/month - the free firebase plan
