### ISSUE TITLE
Any plan for modifying Ark Nova's UI? 

### ISSUE THREAD

**Issue by Ender-Wiggin2019** [ssimeonoff/ssimeonoff.github.io#39]
Hi, I'm not sure whether this is the right place for discussing about the Ark Nova's page, since I find that subpage.  I really like the design for tfm's page, thus I'm wondering if it's possible to modify Ark Nova's UI (to be similar with tfm)? 
Since for now there're only scanned images, and tfm-like UI has faster loading speed, higher resolution icons, and copyable description text. 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/49976407/178116339-a79d8b7c-2a86-476b-a8a5-18e5e40c5952.png">

I took some time to make a sample card, for your reference. By the way, if there're any future plan for the project of Ark Nova, I could do you a favor. 
Thanks a lot for this marvelous work!

**Comment by ssimeonoff** [comment]
@Ender-Wiggin2019 everything is possible. But TM I was not allowed to use images and I need the CSS exercise. Really have no time to do it again.
