### ISSUE TITLE
Unable to login with a gmail

### ISSUE THREAD

**Issue by PlovieJ** [ssimeonoff/ssimeonoff.github.io#41]
I've just discovered your wonderful stat tracker for this amazing game. I've been wanting to keep track of some stats of games I played and this seemed ideal. Having it linked to a gmail for personal stats seemed even better! However, I'm unable to do so. Whenever I click on the Google login, it provides me with options of the google accounts I'm logged in to. I select one of them (I tried both) and it just sends me back to the google login page. It's and endless loop.

I tried to get the error again that popped up regarding being unable to login - something to do with page reload - but I'm unable to make that error pop-up again.

**Comment by r4bBit-s** [comment]
same issue here

**Comment by ssimeonoff** [comment]
most likely the month traffic has been reached and Firebase has disabled the database.
