### ISSUE TITLE
C44 has incorrect Colony Icon

### ISSUE THREAD

**Issue by cyrz** [ssimeonoff/ssimeonoff.github.io#5]
I notice that C44, TITAN FLOATING LAUNCH-PAD has an incorrect icon for the colony. It says "or spend 1 floater here to trade for free.) but the colony icon it shows is the buy colony one. 
![img_1822](https://user-images.githubusercontent.com/12099788/51339425-64adc780-1a5a-11e9-8d23-4ee24650d1da.jpg)

**Comment by ssimeonoff** [comment]
fixed
