### ISSUE TITLE
Jupiter floating station has incorrect icon

### ISSUE THREAD

**Issue by cyrz** [ssimeonoff/ssimeonoff.github.io#7]
Jupiter floating station should have a floater with jovian tag on it. 
<img width="289" alt="screen shot 2019-01-18 at 10 37 25 am" src="https://user-images.githubusercontent.com/12099788/51396487-24f3e800-1b0d-11e9-8dc0-a252f02563c1.png">
<img width="199" alt="screen shot 2019-01-18 at 10 36 36 am" src="https://user-images.githubusercontent.com/12099788/51396502-2cb38c80-1b0d-11e9-92d1-6fcfe2d164d8.png">

**Comment by ssimeonoff** [comment]
fixed
