### ISSUE TITLE
Suggestion: Delete own games

### ISSUE THREAD

**Issue by ap3h3ad** [ssimeonoff/ssimeonoff.github.io#9]
Hi,

another suggestion: Ability to delete own games. E.g. I have mistakenly chosen the wrong corporations, because I checked old photos instead of the new ones. It would be very helpful if a logged in user could delete own games. If you fear manipulation you could implement a timer, so that users can only edit their games (e.g.) for a week.

Greetings!

**Comment by ssimeonoff** [comment]
Will think about the UI/UX. 
Maybe a button "Delete my last game" on the Submit page...
